### ISSUE TITLE
Porymap Support

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokefirered#217]
Now that Fire Red is free of baserom calls, we need to make this a priority somewhere.

- [x] decompile event object movement data
- [ ] layout 21 is missing field(s)

**Comment by ProjectRevoTPP** [comment]
Issue 178 on porymap

**Comment by ProjectRevoTPP** [comment]
https://github.com/huderlem/porymap/issues/180

**Comment by PikalaxALT** [comment]
Resolved in huderlem/porymap#192

**Comment by GriffinRichards** [comment]
Update: closed since [porymap release](https://github.com/huderlem/porymap/releases) 4.0.0 (as of writing now on 4.2.0).
