### ISSUE TITLE
Editing maps layout and rebuilding doesn't update map

### ISSUE THREAD

**Issue by jlaine3333** [pret/pokefirered#386]
To recreate:
Edit any map layout (~/pokefirered/data/layouts/*/map.bin)
Rebuild as leafgreen 1.1 (unsure if it happens with other builds). clearing existing built files or using NODEP=1 argument does not affect the outcome
Reload the map ingame. exiting and reentering the area reveals it does not update (i am aware that the map is stored in the save file and needs to be reloaded by reentering).

**Comment by GriffinRichards** [comment]
Are you editing the `map.bin` directly? `layouts.json` is responsible for generating the files that include the layout bins. If you only edit the `map.bin` they won't be rebuilt. 
Solutions to try:
- Don't edit the `map.bin` directly, use a tool like porymap
- If you want to edit it directly, force it to rebuild by touching/updating `layouts.json`

If you're not only editing the `map.bin`, it's possible something else is going on. scaninc can fail silently and the build will appear to have succeeded, in that case `make clean && make` would stop at and reveal the error (and additionally force `layouts.json` to build).
