### ISSUE TITLE
Removing cut trees in viridian city breaks tutorial man

### ISSUE THREAD

**Issue by jlaine3333** [pret/pokefirered#387]
To recreate:
Remove either or both of the cut tree objects in ~/pokefirered/data/maps/ViridianCity/map.json, making no other changes to the file. Rebuild (currently using leafgreen 1.1, unsure if the issue occurs in other builds). the old man will move ~5 tiles up from his original position and the woman typically next to him will take his place. unaware if this issue occurs beyond the coffee event.

**Comment by GriffinRichards** [comment]
This is not an issue with the repo, but rather your incorrect edits to it. 
Each object on a map has a numbered ID that scripts can use to refer to that object. By deleting the cut tree you're shifting these IDs, and if you do not also update the script then they will refer to the incorrect object. In this particular case this is the ID you'd need to update accordingly <https://github.com/pret/pokefirered/blob/master/data/maps/ViridianCity/scripts.inc#L1>

In the future if you'd like help with the edits you're making please visit #gen-3-help in our Discord
