### ISSUE TITLE
cannot find -lc, -lgcc

### ISSUE THREAD

**Issue by Teloyrks** [pret/pokefirered#493]
I'm trying to compile fire red on a WSL2 Debian distro. I'm following the INSTALL.md
I have installed all the packages and setup DEVKITPRO, DEVKITARM variables correctly.

![image](https://user-images.githubusercontent.com/85334727/157864974-9bfff4c3-a3a3-469f-89c8-443497906a76.png)

my windows version.
![image](https://user-images.githubusercontent.com/85334727/157865287-38ada518-6de1-4ff1-8238-f1587c40264e.png)

when I try to compile with make -j$(nproc)
![image](https://user-images.githubusercontent.com/85334727/157865482-66e0a727-c4c6-4338-b345-561b15ef2927.png)

**Comment by PikalaxALT** [comment]
This usually happens when agbcc was not built correctly. Please inspect the output of `./build.sh` when building agbcc. If you are having issues, please join the discord (link in the README) and ask in #agbcc.
