### ISSUE TITLE
Typo in define for  pokemon_summary_screen.c

### ISSUE THREAD

**Issue by Meister-anon** [pret/pokefirered#592]
at line 2536   the define for GetMovePpPinterYpos  has a typo.

It's missing the "r"  it should be  GetMovePpPrinterYpos

I apologize for not sending a pr, as is typical, 
but I'm not accustomed to working in git, and the repo I'm working in
has substantial changes.

It'd prob be easier for ya'll to just rename the file on your end than try to merge mine.

**Comment by GriffinRichards** [comment]
b8089d184e8484b1ad33ce40b8ef36da437a8ef9
