### ISSUE TITLE
This code does nothing and cannot be right

### ISSUE THREAD

**Issue by hallo1126** [pret/pokefirered#646]
https://github.com/pret/pokefirered/blob/1dd602d91495641448db8e4c711a5348b0316173/src/slot_machine.c#L1685C5-L1689C6

```
for (i = 0; i < NUM_PAYOUT_TYPES - 1; i++)
{
  if (rval < biasChances[i])
    break;
}
```

This code here will get stripped out by any compiler

**Comment by GriffinRichards** [comment]
It does not get stripped out. Note that `i` is used later.

**Comment by hallo1126** [comment]
Oh shit
