### ISSUE TITLE
Event flags (literally)

### ISSUE THREAD

**Issue by rboninsegna** [pret/pokefirered#83]
https://github.com/pret/pokefirered/blob/e4acfdf20b7d56b83cee6f4e49b257a2ecb92a95/include/constants/flags.h#L85-L86 are set by the appropriate DLC scripts after receiving, respectively, the MysticTicket and the AuroraTicket to enable processing of the appropriate item at the Vermilion dock;
0x2F0 and 2F1 record whether the matching introductory text has been seen!

**Comment by PikalaxALT** [comment]
Please open a PR for this, or wait for us to eventually get to documenting these in the course of disassembly.

**Comment by rboninsegna** [comment]
No problem, no hurry - especially if I'd likely give you more work fixing what I'll probably end up breaking :P

(off topic)
And thank you in particular for your early Youtube videos - they're a good part of the reason I started caring "scientifically" about the series :)
