### ISSUE TITLE
How do I utilize the repository and the ROM I built in Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by Stateside-Heavy** [pret/pokefirered#93]
I believe I have a serious knowledge gap. I've been trying for weeks to run this provided build of FireRed, but I can't seem to get the program to run correctly. In Ubuntu, I've successfully built a repository for the game and a ROM to play the game. Then I used mednafen because I read a comment that said that works well. I got that going but whenever I input `mednafen gba` it gives me the  specs and says it's starting but nothing happens. When I've tried to run my rom in the past, it returns "Cannot specify local host" or something like that. Obviously, I should've asked about this while I was doing it so all of this wouldn't currently be so foggy in my brain. Ultimately, my question is this: how do I play FireRed with my own builds, if it is possible?
 ...Upon reviewing my whole paragraph of a question, I also have another, related question. How do I navigate in Ubuntu or any CLI for that matter? This whole thing on mapping locations for files-- I'm super lost. Any help would be mundo mundo appreciated. Thank you for all you do.

**Comment by PikalaxALT** [comment]
You need a Gameboy Advance emulator such as [mGBA](/mgba-emu/mgba). Works best with a display or x11 forwarding.

**Comment by PikalaxALT** [comment]
As for navigation using Linux command line... Well, Google things like terminal, bash, Linux, and posix to get some links to basic tutorials

**Comment by Stateside-Heavy** [comment]
Ok thank you much. I appreciate the advice and tips.
